// Silhouette de navire anti-pollution (avec bras écopeurs / barrages intégrés)
export function createAntiPollutionIcon(color: string, size = 80): ImageData {
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  const s = size / 100;
  ctx.save();
  ctx.translate(size / 2, size / 2);
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  const strokeWidth = Math.max(1.5, size * 0.035);
  ctx.lineWidth = strokeWidth;
  ctx.strokeStyle = '#000';
  ctx.fillStyle = color;
  ctx.beginPath();
  ctx.moveTo(-26 * s, -12 * s);
  ctx.lineTo(-8 * s, -22 * s);
  ctx.lineTo(-8 * s, -14 * s);
  ctx.lineTo(-20 * s, -6 * s);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(26 * s, -12 * s);
  ctx.lineTo(8 * s, -22 * s);
  ctx.lineTo(8 * s, -14 * s);
  ctx.lineTo(20 * s, -6 * s);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(0, -28 * s);
  ctx.lineTo(10 * s, -16 * s);
  ctx.lineTo(11 * s, 28 * s);
  ctx.lineTo(-11 * s, 28 * s);
  ctx.lineTo(-10 * s, -16 * s);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  ctx.beginPath();
  ctx.rect(-5 * s, -6 * s, 10 * s, 14 * s);
  ctx.fill();
  ctx.stroke();
  ctx.strokeStyle = '#ffffff';
  ctx.lineWidth = Math.max(1.2, size * 0.025);
  ctx.beginPath();
  ctx.arc(0, 16 * s, 4 * s, 0, Math.PI, false);
  ctx.stroke();
  ctx.restore();

  return ctx.getImageData(0, 0, size, size);
}